/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sme_util_SauPatchUtil */

#ifndef _Included_com_sme_util_SauPatchUtil
#define _Included_com_sme_util_SauPatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sme_util_SauPatchUtil
 * Method:    patchApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sme_util_SauPatchUtil_patchApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
