/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sme_util_SauDiffUtil */

#ifndef _Included_com_sme_util_SauDiffUtil
#define _Included_com_sme_util_SauDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sme_util_SauDiffUtil
 * Method:    diffApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sme_util_SauDiffUtil_diffApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
